//! Generate besogne.toml from parsed scripts.

use super::ParsedScript;
use std::path::Path;

/// Generate a besogne.toml manifest from parsed scripts.
/// Uses raw string building instead of toml crate serialization
/// for readable, well-commented output.
pub fn generate_toml(scripts: &[ParsedScript], source_path: &Path) -> Result<String, String> {
    let project_name = infer_project_name(source_path);

    let mut out = String::new();

    // Header
    out.push_str(&format!(
        "# Generated by `besogne adopt` from {}\n",
        source_path.file_name().and_then(|f| f.to_str()).unwrap_or("unknown")
    ));
    out.push_str("# Review side_effects fields — besogne caches everything by default.\n");
    out.push_str("# Run `besogne run --verify` to check idempotency.\n\n");

    out.push_str(&format!("name = \"{project_name}\"\n"));
    out.push_str(&format!(
        "description = \"Adopted from {}\"\n\n",
        source_path.file_name().and_then(|f| f.to_str()).unwrap_or("source")
    ));

    // Collect all unique binaries across all scripts
    let mut all_binaries: Vec<String> = scripts
        .iter()
        .flat_map(|s| s.binaries.iter().cloned())
        .collect();
    all_binaries.sort();
    all_binaries.dedup();

    // Filter out npm-internal commands that don't need binary inputs
    let npm_internals = [
        "npm", "yarn", "pnpm", "bun", "npx", "bunx", "pnpx", "node",
    ];

    // Binary inputs
    for binary in &all_binaries {
        if npm_internals.contains(&binary.as_str()) {
            // Still declare node/npm as binaries — they're real executables
            if matches!(binary.as_str(), "node" | "npm" | "yarn" | "pnpm" | "bun") {
                out.push_str(&format!("[inputs.{binary}]\n"));
                out.push_str("type = \"binary\"\n\n");
            }
            continue;
        }
        out.push_str(&format!("[inputs.{}]\n", sanitize_toml_key(binary)));
        out.push_str("type = \"binary\"\n\n");
    }

    // Command inputs
    for script in scripts {
        out.push_str(&format!(
            "[inputs.{}]\n",
            sanitize_toml_key(&script.name)
        ));
        out.push_str("type = \"command\"\n");
        out.push_str("phase = \"exec\"\n");

        // Use shell form for complex scripts, array for simple ones
        let run_spec = format_run_spec(&script.body);
        out.push_str(&run_spec);

        if !script.parents.is_empty() {
            let deps: Vec<String> = script
                .parents
                .iter()
                .map(|d| format!("\"{}\"", sanitize_toml_key(d)))
                .collect();
            out.push_str(&format!("parents = [{}]\n", deps.join(", ")));
        }

        if script.side_effects {
            out.push_str("side_effects = true\n");
        }

        out.push('\n');
    }

    Ok(out)
}

/// Infer project name from source path (package.json → parent dir name)
fn infer_project_name(source_path: &Path) -> String {
    source_path
        .parent()
        .and_then(|p| p.file_name())
        .and_then(|f| f.to_str())
        .unwrap_or("project")
        .to_string()
}

/// Format the run specification for TOML output
fn format_run_spec(body: &str) -> String {
    // If simple single command (no shell operators), use array form
    let has_shell_ops = body.contains("&&")
        || body.contains("||")
        || body.contains('|')
        || body.contains(';')
        || body.contains('>')
        || body.contains('<')
        || body.contains('$')
        || body.contains('`')
        || body.contains('(')
        || body.contains('"')
        || body.contains('\'');

    if has_shell_ops {
        // Shell form: run = "complex command"
        let escaped = body.replace('\\', "\\\\").replace('"', "\\\"");
        format!("run = \"{escaped}\"\n")
    } else {
        // Array form: run = ["cmd", "arg1", "arg2"]
        let parts: Vec<&str> = body.split_whitespace().collect();
        if parts.is_empty() {
            return "run = [\"true\"]\n".to_string();
        }
        let formatted: Vec<String> = parts.iter().map(|p| format!("\"{p}\"")).collect();
        format!("run = [{}]\n", formatted.join(", "))
    }
}

/// Sanitize a string to be a valid TOML key (replace special chars with _)
fn sanitize_toml_key(key: &str) -> String {
    key.chars()
        .map(|c| {
            if c.is_alphanumeric() || c == '_' || c == '-' {
                c
            } else {
                '_'
            }
        })
        .collect()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_format_run_spec_simple() {
        let result = format_run_spec("jest --coverage");
        assert_eq!(result, "run = [\"jest\", \"--coverage\"]\n");
    }

    #[test]
    fn test_format_run_spec_complex() {
        let result = format_run_spec("tsc && webpack --mode production");
        assert_eq!(result, "run = \"tsc && webpack --mode production\"\n");
    }

    #[test]
    fn test_sanitize_toml_key() {
        assert_eq!(sanitize_toml_key("build:prod"), "build_prod");
        assert_eq!(sanitize_toml_key("test-unit"), "test-unit");
        assert_eq!(sanitize_toml_key("lint:fix"), "lint_fix");
    }

    #[test]
    fn test_generate_toml() {
        let scripts = vec![
            ParsedScript {
                name: "build".into(),
                body: "tsc".into(),
                binaries: vec!["tsc".into()],
                env_vars: vec![],
                parents: vec![],
                side_effects: false,
            },
            ParsedScript {
                name: "test".into(),
                body: "jest --coverage".into(),
                binaries: vec!["jest".into()],
                env_vars: vec![],
                parents: vec!["build".into()],
                side_effects: false,
            },
            ParsedScript {
                name: "deploy".into(),
                body: "kubectl apply -f k8s/".into(),
                binaries: vec!["kubectl".into()],
                env_vars: vec![],
                parents: vec!["build".into(), "test".into()],
                side_effects: true,
            },
        ];

        let result = generate_toml(&scripts, Path::new("/app/package.json")).unwrap();

        assert!(result.contains("[inputs.tsc]"));
        assert!(result.contains("[inputs.jest]"));
        assert!(result.contains("[inputs.kubectl]"));
        assert!(result.contains("[inputs.build]"));
        assert!(result.contains("[inputs.test]"));
        assert!(result.contains("[inputs.deploy]"));
        assert!(result.contains("side_effects = true"));
        assert!(result.contains("parents = [\"build\", \"test\"]"));
    }
}
