#!/bin/sh
# Level 2: intermediate — calls level3, uses command substitution, process substitution
set -e

echo "level2: start (pid=$$)"

# Call level 3
sh ./level3.sh

# Command substitution — capture output of a subshell
STAMP=$(date +%s)
echo "level2: stamp=$STAMP" >> results/level2.txt

# Heredoc to a file
cat > results/heredoc.txt <<EOF
generated by level2
stamp=$STAMP
nested=true
EOF

# Subshell with multiple commands
(
  echo "subshell: start"
  sleep 0.05
  echo "subshell: end"
) >> results/level2.txt

echo "level2: done"
