#!/bin/sh
set -e
echo "level2: start (pid=$$)"
sh ./level3.sh
STAMP=$(date +%s)
echo "level2: stamp=$STAMP" >> results/level2.txt
cat > results/heredoc.txt <<EOF
generated by level2
stamp=$STAMP
nested=true
EOF
(echo "subshell: start"; sleep 0.05; echo "subshell: end") >> results/level2.txt
echo "level2: done"
