#!/bin/sh
# Level 2: intermediate — calls level3, uses command substitution
set -e

echo "level2: start project=$PROJECT_NAME (pid=$$)"

# Call level 3
sh ./level3.sh

# Command substitution — capture output of a subshell
STAMP=$(date +%s)
echo "level2: project=$PROJECT_NAME stamp=$STAMP" >> $OUTPUT_PREFIX/level2.txt

# Heredoc to a file
cat > $OUTPUT_PREFIX/heredoc.txt <<EOF
generated by level2
project=$PROJECT_NAME
stamp=$STAMP
nested=true
EOF

# Subshell with multiple commands
(
  echo "subshell: start project=$PROJECT_NAME"
  sleep $SLEEP_DELAY
  echo "subshell: end"
) >> $OUTPUT_PREFIX/level2.txt

echo "level2: done"
